"""Core foundation module for PVT calculations.

This module provides fundamental constants, unit conversions, and exception
classes used throughout the pvtcore package.
"""

from . import constants
from . import units
from . import errors

# Export constants
from .constants import (
    R,
    STP,
    NTP,
    SC_IMPERIAL,
    SC_METRIC,
    SATP,
    STANDARD_CONDITIONS,
    get_standard_condition,
    AVOGADRO_NUMBER,
    BOLTZMANN_CONSTANT,
    PLANCK_CONSTANT,
    ATM_TO_PA,
    BAR_TO_PA,
    PSI_TO_PA,
    ZERO_CELSIUS_IN_KELVIN,
    L_TO_M3,
    FT3_TO_M3,
    BBL_TO_M3,
    LB_TO_KG,
    STANDARD_GRAVITY,
    MW_AIR,
)

# Export unit conversion functions
from .units import (
    # Temperature
    celsius_to_kelvin,
    kelvin_to_celsius,
    fahrenheit_to_celsius,
    celsius_to_fahrenheit,
    fahrenheit_to_kelvin,
    kelvin_to_fahrenheit,
    rankine_to_kelvin,
    kelvin_to_rankine,
    # Pressure
    bar_to_pa,
    pa_to_bar,
    psi_to_pa,
    pa_to_psi,
    atm_to_pa,
    pa_to_atm,
    mpa_to_pa,
    pa_to_mpa,
    kpa_to_pa,
    pa_to_kpa,
    torr_to_pa,
    pa_to_torr,
    bar_to_psi,
    psi_to_bar,
    bar_to_atm,
    atm_to_bar,
    # Volume
    liter_to_m3,
    m3_to_liter,
    ft3_to_m3,
    m3_to_ft3,
    bbl_to_m3,
    m3_to_bbl,
    gallon_to_m3,
    m3_to_gallon,
    cm3_per_mol_to_m3_per_mol,
    m3_per_mol_to_cm3_per_mol,
    liter_per_mol_to_m3_per_mol,
    m3_per_mol_to_liter_per_mol,
    # Mass and molar
    lb_to_kg,
    kg_to_lb,
    lbmol_to_mol,
    mol_to_lbmol,
    # Energy
    cal_to_joule,
    joule_to_cal,
    btu_to_joule,
    joule_to_btu,
    kwh_to_joule,
    joule_to_kwh,
    # Density
    sg_to_density,
    density_to_sg,
    api_to_sg,
    sg_to_api,
)

# Export exceptions
from .errors import (
    PVTError,
    ConvergenceError,
    CharacterizationError,
    CompositionError,
    PhaseError,
    ValidationError,
    EOSError,
    PropertyError,
    DataError,
    UnitError,
    ConfigurationError,
)

__all__ = [
    # Submodules
    'constants',
    'units',
    'errors',
    # Constants
    'R',
    'STP',
    'NTP',
    'SC_IMPERIAL',
    'SC_METRIC',
    'SATP',
    'STANDARD_CONDITIONS',
    'get_standard_condition',
    'AVOGADRO_NUMBER',
    'BOLTZMANN_CONSTANT',
    'PLANCK_CONSTANT',
    'ATM_TO_PA',
    'BAR_TO_PA',
    'PSI_TO_PA',
    'ZERO_CELSIUS_IN_KELVIN',
    'L_TO_M3',
    'FT3_TO_M3',
    'BBL_TO_M3',
    'LB_TO_KG',
    'STANDARD_GRAVITY',
    'MW_AIR',
    # Temperature conversions
    'celsius_to_kelvin',
    'kelvin_to_celsius',
    'fahrenheit_to_celsius',
    'celsius_to_fahrenheit',
    'fahrenheit_to_kelvin',
    'kelvin_to_fahrenheit',
    'rankine_to_kelvin',
    'kelvin_to_rankine',
    # Pressure conversions
    'bar_to_pa',
    'pa_to_bar',
    'psi_to_pa',
    'pa_to_psi',
    'atm_to_pa',
    'pa_to_atm',
    'mpa_to_pa',
    'pa_to_mpa',
    'kpa_to_pa',
    'pa_to_kpa',
    'torr_to_pa',
    'pa_to_torr',
    'bar_to_psi',
    'psi_to_bar',
    'bar_to_atm',
    'atm_to_bar',
    # Volume conversions
    'liter_to_m3',
    'm3_to_liter',
    'ft3_to_m3',
    'm3_to_ft3',
    'bbl_to_m3',
    'm3_to_bbl',
    'gallon_to_m3',
    'm3_to_gallon',
    'cm3_per_mol_to_m3_per_mol',
    'm3_per_mol_to_cm3_per_mol',
    'liter_per_mol_to_m3_per_mol',
    'm3_per_mol_to_liter_per_mol',
    # Mass and molar conversions
    'lb_to_kg',
    'kg_to_lb',
    'lbmol_to_mol',
    'mol_to_lbmol',
    # Energy conversions
    'cal_to_joule',
    'joule_to_cal',
    'btu_to_joule',
    'joule_to_btu',
    'kwh_to_joule',
    'joule_to_kwh',
    # Density conversions
    'sg_to_density',
    'density_to_sg',
    'api_to_sg',
    'sg_to_api',
    # Exceptions
    'PVTError',
    'ConvergenceError',
    'CharacterizationError',
    'CompositionError',
    'PhaseError',
    'ValidationError',
    'EOSError',
    'PropertyError',
    'DataError',
    'UnitError',
    'ConfigurationError',
]
